# Generated by Django 4.0.6 on 2022-08-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='value',
            new_name='text',
        ),
    ]
