# Generated by Django 4.0.6 on 2022-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_value_message_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
    ]
